var base_url=window.location.href.indexOf("mordorintelligence")!=-1?"https://express.mordorintelligence.com":window.location.href.indexOf("mordorlabs")!=-1?"https://express.mordorlabs.com":"http://localhost:8080"
var mordor_url=window.location.href.indexOf("mordorintelligence")!=-1?"https://www.mordorintelligence.com":window.location.href.indexOf("mordorlabs")!=-1?"https://minext.mordorlabs.com":"http://localhost:8080"
let customize_error=false;const email_regex=/^(([^<>()\[\]\\.,;:\s@"]+(\.[^<>()\[\]\\.,;:\s@"]+)*)|(".+"))@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}])|(([a-zA-Z\-0-9]+\.)+[a-zA-Z]{2,}))$/;$('#customizeFrommodal').on('shown.bs.modal',function(e){$('#customize_email').val('');$('#customize_adress').val('');});$('#customize_email').on('input',function(e){let helperText='';if(e.target.value&&!email_regex.test(e.target.value)){document.querySelector('#modalcustomize_email_error').style.display="block";helperText="Please enter a valid email";document.querySelector('#modalcustomize_email_error').innerText=helperText;customize_error=true;}else if(e.target.value.length){let genericEmail=verifyGenericEmail(e.target.value);if(["generic"].indexOf(genericEmail)>-1){document.querySelector('#modalcustomize_email_error').style.display="block";helperText="Please enter your business email";document.querySelector('#modalcustomize_email_error').innerText=helperText;customize_error=true;}
else{customize_error=false;document.querySelector('#modalcustomize_email_error').style.display="none";}}
else if(!e.target.value&&!e.target.value.trim().length){document.querySelector('#modalcustomize_email_error').style.display="block";helperText="Please enter a valid email id";document.querySelector('#modalcustomize_email_error').innerText=helperText;customize_error=true;}});function verifyGenericEmail(email){var domain_full=(email.split('@'))[1];var domain_name=(domain_full.split('.'))[0];var domain_surname=(domain_full.split('.'))[domain_full.split('.').length-1];var domain_arr=["gmail","yahoo","hotmail","aol","msn","wanadoo","orange","comcast","live","rediffmail","free","gmx","web","yandex","ymail","libero","outlook","mail","googlemail","rocketmail","freenet","mac","icloud"];var list_of_generic_emails=domain_arr;if(list_of_generic_emails.indexOf(domain_name)!==-1||email.indexOf("naver")!==-1){return 'generic';}else if(domain_surname==='edu'||domain_full.indexOf(".ac.")!==-1||email.indexOf("student")!==-1){return 'educational';}else
return 'valid';}
$('#customize_adress').on('input',function(e){if(!e.target.value){document.querySelector('#modalcustomize_adress_error').style.display="block";customize_error=true;}else{customize_error=false;document.querySelector('#modalcustomize_adress_error').style.display="none";}})
$('#modalcustmzeSubmtBtn').on('click',function(e){e.preventDefault();let customizeEMailError=$('#customize_email').val();if(customizeEMailError==""||!email_regex.test(customizeEMailError)){document.querySelector('#modalcustomize_email_error').style.display="block";customize_error=true;}else{customize_error=false;document.querySelector('#modalcustomize_email_error').style.display="none";}
if($('#customize_adress').val()==""){document.querySelector('#modalcustomize_adress_error').style.display="block";customize_error=true;}
else{customize_error=false;document.querySelector('#modalcustomize_adress_error').style.display="none";}
if(customizeEMailError!=""&&email_regex.test(customizeEMailError)&&!customize_error){document.querySelector('#modalcustomize-loader').style.display="block";console.log("reportdata",report_data);const body=JSON.stringify({"email":$('#customize_email').val().trim(),"is_blog_lead":JSON.parse(localStorage.getItem('visited_blog'))||false,"desc":$('#customize_adress').val().trim(),"cta":"customization","rep_id":report_data.id,"model_report_id":report_data.id,"model_report_name":report_data.title,"rep_title":report_data.title,"model_cat_id":report_data.category_id,"model_sub_cat_id":report_data.sub_category_id,"model_cat_name":report_data.category_name,"model_sub_cat_name":report_data.sub_category_name,"url":window.location.href,"source_url":window.location.href,"customsource_url":window.location.href,"custom_user_session_id":new Date().getTime(),"cta_text":"Customize The Report"})
fetch(`${base_url}/api/leads`,{method:'post',body}).then(res=>{if(res.ok&&res.status===200){return res.json();}else{throw new Error('Something went wrong');}}).then(res=>{setSessionConversion(window,$('#customize_email').val(),"customize");$('#customizeFrommodal').modal('hide');document.querySelector('#modalcustomize-loader').style.display='none';$('#successModal').modal('show');document.querySelector('.success_content').innerText="You will receive the requested sample via email.";let event_type="form-submit";let event_props={"form_type":amplitude_events.form_type,"event_category":amplitude_events.event_type,"email":$('#customize_email').val().trim(),"is_blog_lead":JSON.parse(localStorage.getItem('visited_blog'))||false,"cat_id":report_data.category_id,"sub_cat_id":report_data.sub_category_id,"category":report_data.category_name,"hub_id":report_data.hub_id?report_data.hub_id:null,"lead_id":res.lead_id,"cta_text":"Customize The Report","related_tags":report_data.related_tags.length?report_data.related_tags:null,"source":window.location.href.includes("gclid")||window.location.href.includes("fbclid")?"Paid":"Organic","landing_page":window.location.href}
amplitude.getInstance().setUserProperties({email:$('#customize_email').val().trim(),lead_id:res.lead_id,application:"website"});amplitude.getInstance().logEvent(event_type,event_props);console.log("customize submit");let wisepop=document.getElementById('wisepops-root');if(wisepop){wisepop.style.display='none';}
console.log(report_data)
if(report_data.category_id===59&&report_data.sample_info&&report_data.sample_info.hasOwnProperty('sample_url')&&report_data.sample_info.sample_url){if(localStorage){var local_storage_lead_array;if(!localStorage['lead_id']){local_storage_lead_array=[];}
else{local_storage_lead_array=JSON.parse(localStorage['lead_id']);}
local_storage_lead_array.push(res.lead_id);localStorage.setItem("lead_id",JSON.stringify(local_storage_lead_array))
var childElement=document.createElement('div');childElement.id="timer";childElement.innerHTML='Redirecting to the sample in <span id="count"></span> second(s).'
childElement.style='text-align:center; color:rgb(229, 37, 99); font-size:16px'
var parentElement=document.getElementById("success_modal_body");parentElement.appendChild(childElement);var count=5;var redirect=`${mordor_url}/industry-reports/sample/${report_data.slug}?lead_id=${res.lead_id}`;var elem=document.getElementById('count');elem.innerText=count
var interval=setInterval(()=>{count--
elem.innerText=count
if(count==0){clearInterval(interval);$('#timer').remove();$('#successModal').modal('hide');window.location.href=redirect;}},1000)}}}).catch((error)=>{console.log(error,'lead failure')
$('#customizeFrommodal').modal('hide');document.querySelector('#modalcustomize-loader').style.display='none';$('#failureModal').modal('show');document.querySelector('.failure_content').innerText="Something went wrong. Please try again later or refresh."})}});$('.customize-close').click(function(e){let email=$('#customize_email').val()
let desc=$('#customize_address').val()});$('#customizeFrommodal').on('hidden.bs.modal',function(e){document.querySelector('#modalcustomize_email_error').style.display="none";document.querySelector('#modalcustomize_adress_error').style.display="none";let customize_loader=document.querySelector('#customize-loader');if(customize_loader&&customize_loader.style){customize_loader.style.display='none';}});